import { writeFileSync, mkdirSync } from 'fs';
import { dirname, resolve } from 'path';
import { Config, OwnershipResult, CodeOwnersEntry } from '../types';
import { OwnershipAnalyzer } from './ownership-analyzer';

export class CodeOwnersGenerator {
  private config: Config;
  private analyzer: OwnershipAnalyzer;

  constructor(config: Config) {
    this.config = config;
    this.analyzer = new OwnershipAnalyzer(config);
  }

  generate(ownershipResults: OwnershipResult[]): string {
    const entries = this.buildEntries(ownershipResults);
    return this.formatCodeOwners(entries);
  }

  private buildEntries(ownershipResults: OwnershipResult[]): CodeOwnersEntry[] {
    const entries: CodeOwnersEntry[] = [];

    if (this.config.preferFolderLevel) {
      // Try to consolidate at folder level
      const folderMap = this.analyzer.groupByFolder(ownershipResults);

      // Sort folders by depth (deeper first) to ensure more specific rules come first
      const sortedFolders = Array.from(folderMap.keys()).sort((a, b) => {
        const depthA = a.split('/').length;
        const depthB = b.split('/').length;
        return depthB - depthA; // Deeper folders first
      });

      const processedFiles = new Set<string>();

      for (const folder of sortedFolders) {
        const files = folderMap.get(folder)!;

        if (this.analyzer.canConsolidateFolder(files)) {
          // All files in folder have same owners - create folder-level entry
          const owners = files[0].owners;

          if (owners.length > 0) {
            entries.push({
              pattern: `${folder}/**`,
              owners,
              comment: `Folder-level ownership (${files.length} files)`
            });

            // Mark all files as processed
            files.forEach(f => processedFiles.add(f.file));
          }
        }
      }

      // Add file-level entries for non-consolidated files
      for (const result of ownershipResults) {
        if (!processedFiles.has(result.file) && result.owners.length > 0) {
          entries.push({
            pattern: result.file,
            owners: result.owners,
            comment: this.getOwnershipComment(result)
          });
        }
      }
    } else {
      // File-level only
      for (const result of ownershipResults) {
        if (result.owners.length > 0) {
          entries.push({
            pattern: result.file,
            owners: result.owners,
            comment: this.getOwnershipComment(result)
          });
        }
      }
    }

    return entries;
  }

  private getOwnershipComment(result: OwnershipResult): string {
    const topContributor = result.stats[0];
    if (!topContributor) {
      return '';
    }

    const percentage = topContributor.percentage.toFixed(1);
    const commits = topContributor.commitCount;

    switch (result.ownershipType) {
      case 'clear-majority':
        return `${percentage}% (${commits} commits)`;
      case 'top-contributors':
        return `Top ${result.owners.length} contributors`;
      case 'default':
        return 'Default owner';
      default:
        return '';
    }
  }

  private formatCodeOwners(entries: CodeOwnersEntry[]): string {
    const lines: string[] = [];

    // Add header
    lines.push('# CODEOWNERS');
    lines.push('# Auto-generated by smart-codeowners');
    lines.push(`# Generated on: ${new Date().toISOString()}`);
    lines.push('#');
    lines.push('# This file defines code ownership for this repository.');
    lines.push('# Each line is a file pattern followed by one or more owners.');
    lines.push('# Owners will be requested for review when someone opens a pull request.');
    lines.push('#');
    lines.push('# More info: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners');
    lines.push('');

    // Add default owner if configured
    if (this.config.defaultOwner) {
      lines.push('# Default owner for everything');
      lines.push(`* ${this.config.defaultOwner}`);
      lines.push('');
    }

    // Group entries by folder for better organization
    const folderEntries = new Map<string, CodeOwnersEntry[]>();
    const rootEntries: CodeOwnersEntry[] = [];

    for (const entry of entries) {
      if (entry.pattern.includes('/')) {
        const folder = entry.pattern.split('/')[0];
        if (!folderEntries.has(folder)) {
          folderEntries.set(folder, []);
        }
        folderEntries.get(folder)!.push(entry);
      } else {
        rootEntries.push(entry);
      }
    }

    // Add root-level entries
    if (rootEntries.length > 0) {
      lines.push('# Root-level files');
      for (const entry of rootEntries) {
        lines.push(this.formatEntry(entry));
      }
      lines.push('');
    }

    // Add folder-based entries
    const sortedFolders = Array.from(folderEntries.keys()).sort();
    for (const folder of sortedFolders) {
      const entries = folderEntries.get(folder)!;

      lines.push(`# ${folder}/`);
      for (const entry of entries) {
        lines.push(this.formatEntry(entry));
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  private formatEntry(entry: CodeOwnersEntry): string {
    const owners = entry.owners.join(' ');
    let line = `${entry.pattern} ${owners}`;

    if (entry.comment) {
      // Pad to align comments
      const padding = Math.max(1, 60 - line.length);
      line += ' '.repeat(padding) + `# ${entry.comment}`;
    }

    return line;
  }

  writeToFile(content: string, outputPath?: string): void {
    const path = outputPath || this.config.outputPath || '.github/CODEOWNERS';
    const fullPath = resolve(process.cwd(), path);

    // Create directory if it doesn't exist
    const dir = dirname(fullPath);
    mkdirSync(dir, { recursive: true });

    // Write file
    writeFileSync(fullPath, content, 'utf-8');

    console.log(`CODEOWNERS file written to: ${fullPath}`);
  }

  async generateAndWrite(ownershipResults: OwnershipResult[], outputPath?: string): Promise<string> {
    const content = this.generate(ownershipResults);
    this.writeToFile(content, outputPath);
    return content;
  }
}
